# Generated by Django 5.0.1 on 2024-02-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.CharField(default=5, verbose_name='Оценка'),
        ),
    ]
