# Generated by Django 5.0.1 on 2024-03-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_timestamp'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
